#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
diff doc ~ compares working to head
diff doc 1 ~ compares working to 1 version back
diff doc 0 1 ~ compares last stored version to 1 back
EOF
}



if [ $# -eq 3 ]; then
    diff d/`./gethead $1 $2` d/`./gethead $1 $3`
elif [ $# -eq 2 ]; then
    diff $1 d/`./gethead $1 $2`
elif [ $# -eq 1 ]; then
    diff $1 d/`./gethead $1`
else
    showUsage
fi