#!/bin/bash
. j4m-funcs

showUsage() {
    cat <<EOF
Usage: 
store wrk "the comment" ~ stores the workign doc to index
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    hash=`j4m-toblob $DOC`
    UN="$USER@$HOSTNAME"
    j4m-toindex $DOC "$hash" `cat .j4m/${DOC}.src` "$UN" "$2"
    echo "$hash" | cat > .j4m/$DOC.src
else
    showUsage
fi

