#!/bin/bash

usage() {
    echo "j4m store wrk \"the comment\""
}

getdoc(){
    VAL=$1
    if [ "$1" == ":today" ]; then
	VAL=`date --rfc-3339=date`
    fi    
    echo "$VAL"
}

DOC=$(getdoc $1)

hash=`j4m-toblob $DOC`
un="$USER@$HOSTNAME"
j4m-toindex $DOC "$hash" `cat .j4m/${DOC}.src` "$un" "$2"
echo "$hash" | cat > .j4m/$DOC.src