#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
create doc ~ creates a doc and index and src files
EOF
}

j4m-init

if [ $# -eq 1 ]; then
    NAME=$1
    if [ "$1" == ":today" ]; then
	NAME=`date --rfc-3339=date`
    fi

    touch .j4m/${NAME}
    touch .j4m/${NAME}.index
    echo "00000000000000000000000000000000" | cat >> .j4m/${NAME}.src
else
    showUsage
fi
