#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
link doc ~ links doc in .j4m to the current dir
EOF
}

if [ $# -eq 1 ]; then
    NAME=$1
    if [ "$1" == ":today" ]; then
	NAME=`date --rfc-3339=date`
    fi

    ln -s .j4m/${NAME} ./${NAME}
else
    showUsage
fi

