#!/bin/bash
. j4m-funcs

showUsage() {
    cat <<EOF
Usage: 
create doc ~ creates a doc and index and src files
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    touch .j4m/${DOC}
    touch .j4m/${DOC}.index
    echo "00000000000000000000000000000000" | cat >> .j4m/${DOC}.src
else
    showUsage
fi
