#!/bin/bash
. j4m-funcs

showUsage() {
    cat <<EOF
Usage: 
cat doc ~ cats a document last store point
cat doc 1 ~ cats a document's previous point :todo
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    tail -n 1 .j4m/${DOC}.index | awk -F'\t' '{ print ".j4m/d/" $1 }' | xargs cat
else
    showUsage
fi

