#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
diff doc ~ compares working to head
diff doc 1 ~ compares working to 1 version back
diff doc 0 1 ~ compares last stored version to 1 back
EOF
}

getdoc(){
    VAL=$1
    if [ "$1" == ":today" ]; then
	VAL=`date --rfc-3339=date`
    fi    
    echo "$VAL"
}


if [ $# -eq 3 ]; then
    DOC=$(getdoc $1)
    diff .j4m/d/`j4m-gethead $DOC $2` .j4m/d/`j4m-gethead $DOC $3`
elif [ $# -eq 2 ]; then
    DOC=$(getdoc $1)
    diff .j4m/${DOC} .j4m/d/`j4m-gethead $DOC $2`
elif [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    diff .j4m/${DOC} .j4m/d/`j4m-gethead $DOC`
else
    showUsage
fi