#!/bin/bash
. j4m-funcs

showUsage() {
    cat <<EOF
Usage: 
get doc ~ gets working to head
get doc 1 ~ gets working to 1 version back #todo
get doc 0 1 ~ gets last stored version to 1 back #todo
EOF
}

LINE=0

if [ $# -eq 2 ]; then
    let "LINE= $2 + 1"
elif [ $# -eq 1 ]; then
    let "LINE= 1"    
else
    showUsage
fi

if [ ! "0" -eq "$LINE" ]; then
# tail -n $LINE ${1}.index | head -n 1 | awk '{ print $1 }'
    DOC=$(getdoc $1)
    blob=`j4m-gethead $DOC`
    echo "$blob" > .j4m/${DOC}.src
    cat .j4m/d/${blob} > .j4m/$DOC
fi