#!/bin/bash
. j4m-funcs

showUsage() {
    cat <<EOF
Usage: 
link doc ~ links doc in .j4m to the current dir
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    ln -s .j4m/${DOC} ./${DOC}
else
    showUsage
fi
