#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
init ~ creates .mtl 
EOF
}

if [ $# -eq 0 ]; then
    if [ ! -d ".mtl" ] ; then
	mkdir .mtl
	mkdir .mtl/d
	mkdir .mtl/remote
    fi
else
    showUsage
fi
