#!/bin/bash
. mtl-funcs

showUsage() {
    cat <<EOF
Usage: 
store wrk "the comment" ~ stores the workign doc to index
EOF
}

if [ $# -gt 0 ]; then
    DOC=$(getdoc $1)
    hash=`mtl-toblob $DOC`
    src=`cat .mtl/${DOC}.src`
    UN="$USER@$HOSTNAME"
    if [ $hash != $src ] || [[ "$2" != "" ]]; then
	mtl-toindex $DOC "$hash" `cat .mtl/${DOC}.src` "$UN" "$2"
	echo "$hash" | cat > .mtl/$DOC.src
    else
	echo "no changes from last store"
    fi
else
    showUsage
fi

