#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
clone ssh://user@host.com:~/mynotes/test
clone to ssh://user@host.com:~/mynotes/test
EOF
}

### this is just quick proof of concept version 
### later we add a way to store remotes

if [ $# -eq 1 ]; then
	echo "cloning the mtl dir.."
	scp -r ${1} .mtl
	echo "DONE"
elif [ $# -eq 2 ]; then
    if [ $1 == "to" ]; then
	echo "cloning the mtl dir to remote location.."
#ls 	mkdir -p ${2}
	scp -r .mtl ${2}/.mtl
	echo "DONE"
    else
	showUsage
    fi
else
    showUsage
fi

