#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
cat doc mergefile
EOF
}

### this is just quick proof of concept version 

INDEX=".mtl/${1}.index"

if [ $# -eq 2 ]; then
    if [ ! -f $INDEX  ]; then
	touch $INDEX
	echo "new index $1"
    fi
    diff $INDEX $2
    cat $INDEX $2 | sort -u |  sort -k 3 > $INDEX
else
    showUsage
fi

#### find last common src
cat wrk.index sepa wrk2.index | awk '
BEGIN {first=0} 
{if ($2=="-") { first = 1 } else { if (first) { a[x++]=$2 } else { b[$2]=y++ } } } 
END { for (x1=x-1; x1>=0;) {  if (b[a[x1]]) { print a[x1]; break }; x1--;  } }
'
