#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
gethead doc ~ compares working to head
gethead doc:1 ~ compares working to 1 version back
gethead doc:0;1 ~ compares last stored version to 1 back
EOF
}

LINE=1

if [ $# -eq 2 ]; then
    let "LINE= $2 + 1"
elif [ $# -eq 1 ]; then
    let "LINE= 1"    
else
    showUsage
fi
tail -n $LINE .mtl/${1}.index | head -n 1 | awk '{ print $1 }'
