#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
sync doc from ssh://user@host.com:~/mynotes/test
sync doc from :peer
EOF
}

if [ $# -eq 3 ]; then
    if [[ $2 == "from" ]]; then
	
	REM="$3"
	if [[ "$3" =~ ^: ]]; then
	    REM=`cat .mtl/.peers | grep "^:\s" | head -n 1 | cut -f 2`
	    echo "PEERS GHOST IS ON $REM"
	fi
	
# we sync just specific doc
    # copy the remote index here
	echo "DELETING OLD TEMP INDEXES"
	rm .mtl/remote/*
	echo "COPYING REMOTE INDEX TO TEMP"
	scp ${3}/.mtl/${1}.index .mtl/remote/.
    # merge the indexes    for index in .mtl/remote/*.index 
#    do
#	DOC=`echo "$index" | sed 's/.mtl\/remote\/\([a-z0-9_-]*\)\.index/\1/'`
#	echo "MERGING: $DOC"
#	mtl-merge $DOC $index
#    done
    #scp .mtl/${1}.index ${2}/.mtl/
    # copy the blobs that arent already here, copy the missing there
#	for blob in `comm -23 <(cat .mtl/${1}.index | cut -f 1 | uniq | sort) <(cat .mtl/remote/${1}.index | cut -f 1 | uniq | sort)` 
#	do
#	    echo "copying blob to remote: $blob"
#	    scp .mtl/d/$blob ${2}/.mtl/d/.
#	done
	
    #do a 3way diff to merge the files
	
	echo "-" | cat > .mtl/sepa
	
    #### find last common src
	OLDBL=`cat .mtl/${1}.index .mtl/sepa .mtl/remote/${1}.index | awk '
    BEGIN {first=0} 
    {if ($1=="-") { first = 1 } else { if (first) { a[x++]=$1 } else { b[$1]=y++ } } } 
    END { for (x1=x-1; x1>=0;) { if (b[a[x1]]) { print a[x1]; break }; x1--;  } }'`
	
	MYBL=`tail -n 1 .mtl/${1}.index | cut -f 1`
	THEIRBL=`tail -n 1 .mtl/remote/${1}.index | cut -f 1`
	
	if [[ $MYBL == $THEIRBL ]]; then 
	    
	    echo "NO MERGING NECESSARY"

	else
	    
	    echo "GETTING THE BLOBS"
	    for blob in `comm -13 <(cat .mtl/${1}.index | cut -f 1 | uniq | sort) <(cat .mtl/remote/${1}.index | cut -f 1 | uniq | sort)` 
	    do
		echo " COPYING BLOB: $blob"
		scp ${3}/.mtl/d/$blob .mtl/d/.
	    done
	    
	    echo "MERGING MY: $MYBL, OLD: $OLDBL, THEIR: $THEIRBL"
	    
	    echo "diff3 -m .mtl/d/$MYBL .mtl/d/$OLDBL .mtl/d/$THEIRBL | tee .mtl/$1"
	    
	    diff3 -L local -L old -L remote -m .mtl/d/$MYBL .mtl/d/$OLDBL .mtl/d/$THEIRBL | tee .mtl/$1
	    
	# if no conflict
	# create new index with adition of this merge
	# else
	# warn about conflict and that they should merge manually
	fi
	
	echo "DONE"
    else
	showUsage
    fi
else
    showUsage    
fi

