#!/bin/bash
. mtl-funcs

showUsage() {
    cat <<EOF
Usage: 
link doc ~ links doc in .mtl to the current dir
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    ln -s .mtl/${DOC} ./${DOC}
else
    showUsage
fi
