#!/bin/bash
. mtl-funcs

showUsage() {
    cat <<EOF
Usage: 
diff doc ~ compares working to head
diff doc 1 ~ compares working to 1 version back
diff doc 0 1 ~ compares last stored version to 1 back
EOF
}


if [ $# -eq 3 ]; then
    DOC=$(getdoc $1)
    diff -u .mtl/d/`mtl-gethead $DOC $2` .mtl/d/`mtl-gethead $DOC $3`
elif [ $# -eq 2 ]; then
    DOC=$(getdoc $1)
    diff -u .mtl/${DOC} .mtl/d/`mtl-gethead $DOC $2`
elif [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    diff -u .mtl/${DOC} .mtl/d/`mtl-gethead $DOC`
else
    showUsage
fi
