#!/bin/bash
. mtl-funcs

showUsage() {
    cat <<EOF
Usage: 
store wrk "the comment" ~ stores the workign doc to index
EOF
}

if [ $# -eq 1 ]; then
    DOC=$(getdoc $1)
    hash=`mtl-toblob $DOC`
    UN="$USER@$HOSTNAME"
    mtl-toindex $DOC "$hash" `cat .mtl/${DOC}.src` "$UN" "$2"
    echo "$hash" | cat > .mtl/$DOC.src
else
    showUsage
fi

