#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
ls ~ lists all documents
EOF
}

# todo make it accept a pattern like ls

if [ $# -eq 0 ]; then
    ls .mtl/*.index | cut -d "." -f 2 | cut -d "/" -f 2
else
    showUsage
fi

